# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/proto/note.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pi/proto/note.proto\x12\x04note\"\x07\n\x05\x65mpty\"<\n\x11UpdateBoolRequest\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\x12\x16\n\x0e\x62ool_completed\x18\x02 \x01(\x08\"h\n\x04Note\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\x12\x10\n\x08str_text\x18\x02 \x01(\t\x12\x13\n\x0bstr_md_text\x18\x03 \x01(\t\x12\x10\n\x08str_date\x18\x04 \x01(\t\x12\x16\n\x0e\x62ool_completed\x18\x05 \x01(\x08\"d\n\x11\x43reateNoteRequest\x12\x10\n\x08str_text\x18\x01 \x01(\t\x12\x13\n\x0bstr_md_text\x18\x02 \x01(\t\x12\x10\n\x08str_date\x18\x03 \x01(\t\x12\x16\n\x0e\x62ool_completed\x18\x04 \x01(\x08\"!\n\x0eGetNoteRequest\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\"u\n\x11UpdateNoteRequest\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\x12\x10\n\x08str_text\x18\x02 \x01(\t\x12\x13\n\x0bstr_md_text\x18\x03 \x01(\t\x12\x10\n\x08str_date\x18\x04 \x01(\t\x12\x16\n\x0e\x62ool_completed\x18\x05 \x01(\x08\"$\n\x11\x44\x65leteNoteRequest\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\"(\n\x0cNoteResponse\x12\x18\n\x04note\x18\x01 \x01(\x0b\x32\n.note.Note\"%\n\x12\x44\x65leteNoteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x10\x41llNotesResponse\x12\x18\n\x04note\x18\x01 \x03(\x0b\x32\n.note.Note\"\x18\n\nIdResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"\x19\n\nDayRequest\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\t2\x8f\x03\n\x0bNoteService\x12\x37\n\nCreateNote\x12\x17.note.CreateNoteRequest\x1a\x10.note.IdResponse\x12+\n\x07GetNote\x12\x14.note.GetNoteRequest\x1a\n.note.Note\x12\x32\n\x0bGetAllNotes\x12\x0b.note.empty\x1a\x16.note.AllNotesResponse\x12\x38\n\x0cGetNoteByDay\x12\x10.note.DayRequest\x1a\x16.note.AllNotesResponse\x12\x37\n\nUpdateNote\x12\x17.note.UpdateNoteRequest\x1a\x10.note.IdResponse\x12?\n\nDeleteNote\x12\x17.note.DeleteNoteRequest\x1a\x18.note.DeleteNoteResponse\x12\x32\n\nUpdateBool\x12\x17.note.UpdateBoolRequest\x1a\x0b.note.emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.proto.note_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_UPDATEBOOLREQUEST']._serialized_start=39
  _globals['_UPDATEBOOLREQUEST']._serialized_end=99
  _globals['_NOTE']._serialized_start=101
  _globals['_NOTE']._serialized_end=205
  _globals['_CREATENOTEREQUEST']._serialized_start=207
  _globals['_CREATENOTEREQUEST']._serialized_end=307
  _globals['_GETNOTEREQUEST']._serialized_start=309
  _globals['_GETNOTEREQUEST']._serialized_end=342
  _globals['_UPDATENOTEREQUEST']._serialized_start=344
  _globals['_UPDATENOTEREQUEST']._serialized_end=461
  _globals['_DELETENOTEREQUEST']._serialized_start=463
  _globals['_DELETENOTEREQUEST']._serialized_end=499
  _globals['_NOTERESPONSE']._serialized_start=501
  _globals['_NOTERESPONSE']._serialized_end=541
  _globals['_DELETENOTERESPONSE']._serialized_start=543
  _globals['_DELETENOTERESPONSE']._serialized_end=580
  _globals['_ALLNOTESRESPONSE']._serialized_start=582
  _globals['_ALLNOTESRESPONSE']._serialized_end=626
  _globals['_IDRESPONSE']._serialized_start=628
  _globals['_IDRESPONSE']._serialized_end=652
  _globals['_DAYREQUEST']._serialized_start=654
  _globals['_DAYREQUEST']._serialized_end=679
  _globals['_NOTESERVICE']._serialized_start=682
  _globals['_NOTESERVICE']._serialized_end=1081
# @@protoc_insertion_point(module_scope)
