# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/proto/note.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pi/proto/note.proto\x12\x04note\"\x07\n\x05\x65mpty\";\n\x11UpdateBoolRequest\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\x12\x15\n\rbool_complete\x18\x02 \x01(\x08\"h\n\x04Note\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\x12\x10\n\x08str_text\x18\x02 \x01(\t\x12\x13\n\x0bstr_md_text\x18\x03 \x01(\t\x12\x10\n\x08str_date\x18\x04 \x01(\t\x12\x16\n\x0e\x62ool_completed\x18\x05 \x01(\x08\"d\n\x11\x43reateNoteRequest\x12\x10\n\x08str_text\x18\x01 \x01(\t\x12\x13\n\x0bstr_md_text\x18\x02 \x01(\t\x12\x10\n\x08str_date\x18\x03 \x01(\t\x12\x16\n\x0e\x62ool_completed\x18\x04 \x01(\x08\"!\n\x0eGetNoteRequest\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\"u\n\x11UpdateNoteRequest\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\x12\x10\n\x08str_text\x18\x02 \x01(\t\x12\x13\n\x0bstr_md_text\x18\x03 \x01(\t\x12\x10\n\x08str_date\x18\x04 \x01(\t\x12\x16\n\x0e\x62ool_completed\x18\x05 \x01(\x08\"$\n\x11\x44\x65leteNoteRequest\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\"(\n\x0cNoteResponse\x12\x18\n\x04note\x18\x01 \x01(\x0b\x32\n.note.Note\"%\n\x12\x44\x65leteNoteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x10\x41llNotesResponse\x12\x18\n\x04note\x18\x01 \x03(\x0b\x32\n.note.Note\"\x18\n\nIdResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"\x19\n\nDayRequest\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\t2\x97\x03\n\x0bNoteService\x12\x37\n\nCreateNote\x12\x17.note.CreateNoteRequest\x1a\x10.note.IdResponse\x12\x33\n\x07GetNote\x12\x14.note.GetNoteRequest\x1a\x12.note.NoteResponse\x12\x32\n\x0bGetAllNotes\x12\x0b.note.empty\x1a\x16.note.AllNotesResponse\x12\x38\n\x0cGetNoteByDay\x12\x10.note.DayRequest\x1a\x16.note.AllNotesResponse\x12\x37\n\nUpdateNote\x12\x17.note.UpdateNoteRequest\x1a\x10.note.IdResponse\x12?\n\nDeleteNote\x12\x17.note.DeleteNoteRequest\x1a\x18.note.DeleteNoteResponse\x12\x32\n\nUpdateBool\x12\x17.note.UpdateBoolRequest\x1a\x0b.note.emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.proto.note_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_UPDATEBOOLREQUEST']._serialized_start=39
  _globals['_UPDATEBOOLREQUEST']._serialized_end=98
  _globals['_NOTE']._serialized_start=100
  _globals['_NOTE']._serialized_end=204
  _globals['_CREATENOTEREQUEST']._serialized_start=206
  _globals['_CREATENOTEREQUEST']._serialized_end=306
  _globals['_GETNOTEREQUEST']._serialized_start=308
  _globals['_GETNOTEREQUEST']._serialized_end=341
  _globals['_UPDATENOTEREQUEST']._serialized_start=343
  _globals['_UPDATENOTEREQUEST']._serialized_end=460
  _globals['_DELETENOTEREQUEST']._serialized_start=462
  _globals['_DELETENOTEREQUEST']._serialized_end=498
  _globals['_NOTERESPONSE']._serialized_start=500
  _globals['_NOTERESPONSE']._serialized_end=540
  _globals['_DELETENOTERESPONSE']._serialized_start=542
  _globals['_DELETENOTERESPONSE']._serialized_end=579
  _globals['_ALLNOTESRESPONSE']._serialized_start=581
  _globals['_ALLNOTESRESPONSE']._serialized_end=625
  _globals['_IDRESPONSE']._serialized_start=627
  _globals['_IDRESPONSE']._serialized_end=651
  _globals['_DAYREQUEST']._serialized_start=653
  _globals['_DAYREQUEST']._serialized_end=678
  _globals['_NOTESERVICE']._serialized_start=681
  _globals['_NOTESERVICE']._serialized_end=1088
# @@protoc_insertion_point(module_scope)
