# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: note.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnote.proto\x12\x04note\"\x07\n\x05\x65mpty\"h\n\x04Note\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\x12\x10\n\x08str_text\x18\x02 \x01(\t\x12\x13\n\x0bstr_md_text\x18\x03 \x01(\t\x12\x10\n\x08str_date\x18\x04 \x01(\t\x12\x16\n\x0e\x62ool_completed\x18\x05 \x01(\x08\"d\n\x11\x43reateNoteRequest\x12\x10\n\x08str_text\x18\x01 \x01(\t\x12\x13\n\x0bstr_md_text\x18\x02 \x01(\t\x12\x10\n\x08str_date\x18\x03 \x01(\t\x12\x16\n\x0e\x62ool_completed\x18\x04 \x01(\x08\"!\n\x0eGetNoteRequest\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\"u\n\x11UpdateNoteRequest\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\x12\x10\n\x08str_text\x18\x02 \x01(\t\x12\x13\n\x0bstr_md_text\x18\x03 \x01(\t\x12\x10\n\x08str_date\x18\x04 \x01(\t\x12\x16\n\x0e\x62ool_completed\x18\x05 \x01(\x08\"$\n\x11\x44\x65leteNoteRequest\x12\x0f\n\x07id_note\x18\x01 \x01(\x05\"(\n\x0cNoteResponse\x12\x18\n\x04note\x18\x01 \x01(\x0b\x32\n.note.Note\"%\n\x12\x44\x65leteNoteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x10\x41llNotesResponse\x12\x18\n\x04note\x18\x01 \x03(\x0b\x32\n.note.Note2\xad\x02\n\x0bNoteService\x12\x39\n\nCreateNote\x12\x17.note.CreateNoteRequest\x1a\x12.note.NoteResponse\x12\x33\n\x07GetNote\x12\x14.note.GetNoteRequest\x1a\x12.note.NoteResponse\x12\x32\n\x0bGetAllNotes\x12\x0b.note.empty\x1a\x16.note.AllNotesResponse\x12\x39\n\nUpdateNote\x12\x17.note.UpdateNoteRequest\x1a\x12.note.NoteResponse\x12?\n\nDeleteNote\x12\x17.note.DeleteNoteRequest\x1a\x18.note.DeleteNoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'note_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_NOTE']._serialized_start=29
  _globals['_NOTE']._serialized_end=133
  _globals['_CREATENOTEREQUEST']._serialized_start=135
  _globals['_CREATENOTEREQUEST']._serialized_end=235
  _globals['_GETNOTEREQUEST']._serialized_start=237
  _globals['_GETNOTEREQUEST']._serialized_end=270
  _globals['_UPDATENOTEREQUEST']._serialized_start=272
  _globals['_UPDATENOTEREQUEST']._serialized_end=389
  _globals['_DELETENOTEREQUEST']._serialized_start=391
  _globals['_DELETENOTEREQUEST']._serialized_end=427
  _globals['_NOTERESPONSE']._serialized_start=429
  _globals['_NOTERESPONSE']._serialized_end=469
  _globals['_DELETENOTERESPONSE']._serialized_start=471
  _globals['_DELETENOTERESPONSE']._serialized_end=508
  _globals['_ALLNOTESRESPONSE']._serialized_start=510
  _globals['_ALLNOTESRESPONSE']._serialized_end=554
  _globals['_NOTESERVICE']._serialized_start=557
  _globals['_NOTESERVICE']._serialized_end=858
# @@protoc_insertion_point(module_scope)
